version: '3.8'

services:
  frontend:
    container_name: frontend
    build: .
    ports:
      - '5173:5173'
    env_file:
      - .env.development.local
    volumes:
      - .:/app
    stdin_open: true
    tty: true


